In [3]:
import numpy as np

In [9]:
# One Dimentional Array

one_dim_array = np.arange(10)
one_dim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.square(one_dim_array)
np.sqrt(one_dim_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
# Statics of Array
print('one_dim_array = ', one_dim_array)
print('\n')
print(np.max(one_dim_array))
print(np.min(one_dim_array))
print(np.mean(one_dim_array))
print(np.std(one_dim_array))
print(np.var(one_dim_array))

one_dim_array =  [0 1 2 3 4 5 6 7 8 9]


9
0
4.5
2.8722813232690143
8.25


In [13]:
# Slicing of Array
print('one_dim_array = ', one_dim_array)
print('\n')

print(one_dim_array[:5])
print(one_dim_array[5:])
print(one_dim_array[4:7])
print(one_dim_array[::2])
print(one_dim_array[1::2])
print(one_dim_array[::-1])

one_dim_array =  [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [14]:
# Properties of Array
print('one_dim_array = ', one_dim_array)
print('\n')

print(one_dim_array.shape)
print(one_dim_array.size)
print(one_dim_array.dtype)
print(one_dim_array.ndim)

demo = one_dim_array.astype('float')

one_dim_array =  [0 1 2 3 4 5 6 7 8 9]


(10,)
10
int64
1


In [15]:
demo.dtype

dtype('float64')

In [16]:
# List is not an Array

demo_list = ([1, 2, 3], [4, 2, 6], [3, 8, 9])
demo_list

([1, 2, 3], [4, 2, 6], [3, 8, 9])

In [17]:
demo_list + 10

TypeError: can only concatenate tuple (not "int") to tuple

In [18]:
# Multi Dimentional Array

multidim_array = np.array(demo_list)
print(multidim_array)

[[1 2 3]
 [4 2 6]
 [3 8 9]]


In [22]:
multidim_array + 10
multidim_array.flatten()

array([1, 2, 3, 4, 2, 6, 3, 8, 9])

In [23]:
np.unique(multidim_array)

array([1, 2, 3, 4, 6, 8, 9])

In [31]:
# Statics of Multi Dimentional Array
multidim_array.max()
multidim_array.min()
multidim_array.mean()
multidim_array.std()
multidim_array.var()

7.061728395061728

In [33]:
# Slicing of Multi Dimentional Array
print(multidim_array)
print('\n')

print(multidim_array[0])
print(multidim_array[1])
print(multidim_array[-1])
print(multidim_array[:,2])
print(multidim_array[::2])

[[1 2 3]
 [4 2 6]
 [3 8 9]]


[1 2 3]
[4 2 6]
[3 8 9]
[3 6 9]
[[1 2 3]
 [3 8 9]]


In [34]:
# Properties of Multi Dimentional Arry

print(multidim_array.shape)   # np.shape(demo_array) 
print(multidim_array.size)     # np.size(demo_array)   # size(a, axis)
print(multidim_array.dtype)
print(multidim_array.ndim)     # np.ndim(demo_array)

(3, 3)
9
int64
2


In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
ones_array = np.ones((2, 5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.random.rand(2,2)

array([[0.78428823, 0.77972615],
       [0.00258955, 0.63658468]])

In [59]:
np.random.randn(2,3)  # Mean 0 and variance 1

array([[-0.96771552, -0.87025949, -0.47963387],
       [-1.00464829,  1.46649906, -0.29547849]])

In [61]:
# Random Integer

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

In [65]:
x1

array([2, 6, 5, 9, 5, 8])

In [66]:
x2

array([[8, 2, 5, 5],
       [2, 7, 7, 0],
       [7, 0, 9, 5]])

In [67]:
x3

array([[[5, 5, 7, 4, 4],
        [3, 4, 9, 9, 8],
        [4, 3, 5, 9, 6],
        [6, 5, 6, 5, 1]],

       [[0, 6, 7, 1, 0],
        [4, 0, 8, 8, 7],
        [1, 4, 5, 8, 2],
        [6, 4, 4, 9, 9]],

       [[4, 9, 6, 7, 4],
        [4, 1, 1, 7, 7],
        [8, 4, 5, 5, 8],
        [1, 7, 0, 7, 3]]])